// <auto-generated />
namespace SIAH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_active_field_user_account : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_active_field_user_account));
        
        string IMigrationMetadata.Id
        {
            get { return "202005232032435_add_active_field_user_account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
