// <auto-generated />
namespace SIAH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_userID_field_pedidos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_userID_field_pedidos));
        
        string IMigrationMetadata.Id
        {
            get { return "202006202310411_add_userID_field_pedidos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
