// <auto-generated />
namespace SIAH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class alter_table_pedido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_table_pedido));
        
        string IMigrationMetadata.Id
        {
            get { return "202002241602358_alter_table_pedido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
