// <auto-generated />
namespace SIAH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class agregado_saldos_tablas_historicos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregado_saldos_tablas_historicos));
        
        string IMigrationMetadata.Id
        {
            get { return "202104132227034_agregado_saldos_tablas_historicos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
