// <auto-generated />
namespace SIAH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class cantidad_detalle_reclamo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cantidad_detalle_reclamo));
        
        string IMigrationMetadata.Id
        {
            get { return "202103282151075_cantidad_detalle_reclamo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
