// <auto-generated />
namespace SIAH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tipo_reclamo_detalle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tipo_reclamo_detalle));
        
        string IMigrationMetadata.Id
        {
            get { return "202104022305588_tipo_reclamo_detalle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
