// <auto-generated />
namespace SIAH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class creado_tablas_historico : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creado_tablas_historico));
        
        string IMigrationMetadata.Id
        {
            get { return "202104140044500_creado_tablas_historico"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
